# Generated by Django 5.1.2 on 2024-11-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="frequency_in",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Повторение привычки в"
            ),
        ),
    ]
